[+] add new tests

diff --git a/tests/test_dir b/tests/test_dir
--- a/tests/test_dir
+++ b/tests/test_dir
@@ -21,3 +21,28 @@ function test_find_dir () {
 
 test_find_dir "arbre" "season"
 test_find_dir "arbre" "dog"
+
+function test_find_dir_nb () {
+    if [ ! "$(./ftc "$1" "-dir" "$2" | wc -l)" == "$(find "$1" "-name" "$2" "-type" "d" | wc -l)" ];
+    then
+        echo "🔴 Test of find with name failed for file \"$2\""
+        exit 1
+    else
+        echo "✅ Test of find with name succeeded (file: \"$2\")."
+    fi
+}
+
+test_find_dir_nb "arbre" "buy"
+test_find_dir_nb "arbre" "by"
+
+function test_find_dir_regex () {
+    if [ ! "$(./ftc "$1" "-dir" "$2" | wc -l)" == "$(find "$1" "-regex" "$2" "-type" "d" | wc -l)" ];
+    then
+        echo "🔴 Test of find with name failed for file \"$2\""
+        exit 1
+    else
+        echo "✅ Test of find with name succeeded (file: \"$2\")."
+    fi
+}
+
+test_find_dir_regex "arbre" ".*/b[ey]"
