[+] add exit on test failure and add new mime test

diff --git a/tests/test_mime b/tests/test_mime
--- a/tests/test_mime
+++ b/tests/test_mime
@@ -13,7 +13,7 @@ function test_find_mime () {
     then
         echo "🔴 Test of the mime type failed for type \"$2\""
         echo "$(./ftc "$1" "-mime" "$2")"
-        echo "$(find "$1" "-name" "$3")"
+        exit 1
     else
         echo "✅ Test of find with mime type succeeded (type: \"$2\")."
     fi
@@ -21,3 +21,17 @@ function test_find_mime () {
 
 
 test_find_mime "arbre/economic/player/his/a/" "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" "arbre/economic/player/his/a/buy.xlsx"
+
+function test_find_mime_nb() {
+    if [ ! "$(./ftc "$1" "-mime" "$2" | wc -l)" == $3 ];
+    then
+       echo "🔴 Test of the mime type failed for type \"$2\""
+        echo "$(./ftc "$1" "-mime" "$2" | wc -l)"
+        echo "$3"
+        exit 1
+    else
+        echo "✅ Test of find with mime type succeeded (type: \"$2\")."
+    fi
+}
+
+test_find_mime_nb "arbre" "image/png" "     228"
